defmodule Mix.Tasks.Musician.CheckCoverage do
  @moduledoc """
  Reads _build/coverage/coverage.xml (generated by `mix test.coverage`)
  and exits non-zero if any app falls below its per-app threshold.
  """
  use Mix.Task

  @app_thresholds %{
    musician_memory: 90,
    musician_session: 80,
    orchestra: 80,
    musician_tools: 80,
    musician_skills: 80,
    musician_plugins: 85,
    musician_core: 95,
    musician_auth: 80,
    musician_cli: 50,
    musician_tui: 60
  }

  @impl true
  def run(_) do
    coverage_path = "_build/coverage/coverage.xml"

    unless File.exists?(coverage_path) do
      Mix.shell().error("Coverage report not found at #{coverage_path}. Run `mix test --cover` first.")
      System.halt(1)
    end

    failures =
      for {app, min_pct} <- @app_thresholds, into: [] do
        actual = read_app_coverage(coverage_path, app)
        Mix.shell().info("  #{app}: #{actual}% (minimum #{min_pct}%)")
        if actual < min_pct, do: {app, min_pct, actual}, else: nil
      end |> Enum.reject(&is_nil/1)

    if failures != [] do
      Mix.shell().error("\nCoverage below threshold:")
      for {app, min, actual} <- failures do
        Mix.shell().error("  #{app}: #{actual}% (minimum #{min}%)")
      end
      System.halt(1)
    else
      Mix.shell().info("\nAll apps meet coverage thresholds.")
    end
  end

  defp read_app_coverage(path, app) do
    # Parse coverage.xml — each <package name="..."> has a line-rate attribute (0.0-1.0)
    pattern = ~r/<package name="Elixir\.#{Macro.camelize(Atom.to_string(app))}"[^>]*line-rate="([0-9.]+)"/

    case Regex.run(pattern, File.read!(path)) do
      [_, rate] -> (String.to_float(rate) * 100) |> Float.round(1) |> trunc()
      nil -> 0
    end
  end
end
